# Generated by Django 4.2.13 on 2024-05-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imge',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Оценка'),
        ),
    ]
