# Generated by Django 4.2.13 on 2024-05-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_movie_imge_movie_image_alter_movie_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('id',), 'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
    ]
